<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPWyYPS3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPWyYPS3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPWyYPS3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPWyYPS3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPWyYPS3\App_KernelProdContainer([
    'container.build_hash' => 'PWyYPS3',
    'container.build_id' => 'cf0fb15f',
    'container.build_time' => 1708948884,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPWyYPS3');
