<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_page1' => [[], ['_controller' => 'App\\Controller\\AccueilController::page1'], [], [['text', '/premierePage']], [], [], []],
    'app_profil' => [[], ['_controller' => 'App\\Controller\\AccueilController::page3'], [], [['text', '/profil']], [], [], []],
    'app_page2' => [[], ['_controller' => 'App\\Controller\\AccueilController::page2'], [], [['text', '/info']], [], [], []],
    'app_record' => [[], ['_controller' => 'App\\Controller\\AccueilController::record'], [], [['text', '/']], [], [], []],
    'app_contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\AccueilController::page1' => [[], ['_controller' => 'App\\Controller\\AccueilController::page1'], [], [['text', '/premierePage']], [], [], []],
    'App\Controller\AccueilController::page3' => [[], ['_controller' => 'App\\Controller\\AccueilController::page3'], [], [['text', '/profil']], [], [], []],
    'App\Controller\AccueilController::page2' => [[], ['_controller' => 'App\\Controller\\AccueilController::page2'], [], [['text', '/info']], [], [], []],
    'App\Controller\AccueilController::record' => [[], ['_controller' => 'App\\Controller\\AccueilController::record'], [], [['text', '/']], [], [], []],
    'App\Controller\ContactController::index' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\RegistrationController::verifyUserEmail' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
