<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxiX2FC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxiX2FC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxiX2FC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxiX2FC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxiX2FC\App_KernelDevDebugContainer([
    'container.build_hash' => 'WxiX2FC',
    'container.build_id' => 'bf964dbb',
    'container.build_time' => 1710841987,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxiX2FC');
