<?php

namespace ContainerPWyYPS3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtistRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ArtistRepository' shared autowired service.
     *
     * @return \App\Repository\ArtistRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ArtistRepository'] = new \App\Repository\ArtistRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
