<?php

namespace ContainerPWyYPS3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ContactFormType' shared autowired service.
     *
     * @return \App\Form\ContactFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ContactFormType'] = new \App\Form\ContactFormType();
    }
}
