<?php

namespace ContainerPWyYPS3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventSubscriber\ContactSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\ContactSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventSubscriber\\ContactSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\ContactSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\ContactSubscriber'] = new \App\EventSubscriber\ContactSubscriber($a);
    }
}
